name: Run CI, Test

on:
  pull_request:
    branches:
      - main
      - develop
      - release/**

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: ci_environment
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis
        ports:
          - 6379:6379

      mailpit:
        image: axllent/mailpit
        ports:
          - 1025:1025
          - 8025:8025

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Setup PHP, with Composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none

      - name: Install Composer dependencies
        run: composer install

      - name: Install Node Modules
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Generate key application
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Run Seeds
        run: php artisan db:seed

      - name: Run Migrations Rollback
        run: php artisan migrate:rollback --force

      - name: Run Test
        run: php artisan test --parallel
